const USER_LOGGED_IN = "USER_LOGGED_IN";
const USER_LOGGED_OUT = "USER_LOGGED_OUT";
const ADD_COMMENT = 'ADD_COMMENT';
const SET_POSTS = 'SET_POSTS';
const CREATING_POSTS = 'CREATING_POSTS';
const POST_CREATED = 'POST_CREATED';
const LOADING_USER = 'LOADING_USER';
const USER_LOADED = 'USER_LOADED';
const SET_MESSAGE = 'SET_MESSAGE';

export { 
    USER_LOGGED_IN, USER_LOGGED_OUT, ADD_COMMENT, SET_POSTS, CREATING_POSTS, POST_CREATED, LOADING_USER, 
    USER_LOADED, SET_MESSAGE
};