const USER_LOGGED_IN = "USER_LOGGED_IN";
const USER_LOGGED_OUT = "USER_LOGGED_OUT";
const ADD_POST = 'ADD_POST';
const ADD_COMMENT = 'ADD_COMMENT';

export { USER_LOGGED_IN, USER_LOGGED_OUT, ADD_POST, ADD_COMMENT }